interp/interp.go
#3 
Original-awk accepts extra arguments. 
And I found sprintf in interp.go is argment-based interpret, so I fix types-based(array which format specifiers) interpret.
If the number of format specifiers is more than the num of argments, it shows format error message and exit 1.
```
[yugo-horie@goawk 10:53:06]$go run goawk.go 'BEGIN { sprintf("%d ", 1, 2) }'
[yugo-horie@goawk 10:54:17]$go run goawk.go 'BEGIN { sprintf("%d %d", 1, 2) }'
[yugo-horie@goawk 10:54:22]$go run goawk.go 'BEGIN { sprintf("%d %d %d", 1, 2) }'
format error: got 2 args, expected 3
exit status 1
```
If it's looks good for you please merge it.
=> interpret sprintf args in types-base #3

TODO.txt, goawk.go, interp/functions.go, interp/interp.go, interp/interp_test.go, interp/io.go
This is useful for running scripts from untrusted user input.
=> Add config options for "safe mode" to prevent exec and file reads/writes

-ftest, goawk.go, goawk_test.go
This matches the behavior of AWK, Gawk, and Mawk.
This PR also add tests for command line arg errors.
Fixes #53
=> Add support for "--", stop parsing flags when arg not prefixed with "-"

interp/functions.go, interp/interp.go, interp/interp_test.go, interp/io.go
Attempt at fixing #59.
I checked the test suite (`go test ./... -v`) - seems all green.
1. Though I feel would be good to add some more tests for this specific case, but I'm a bit unsure how exactly. The test suite in `interp_test.go` doen't have means for provinding environment variables to test. Would be glad for an advice.
2. Hopefully I changed `sh` -> `/bin/sh` in all relevant places (to cover `system()`, `"cmd" | getline`, `print | "cmd"`). But now it feels like a bit of copy-paste. Do you think it makes sense to do something about this - like extracting a function or a constant? If yes, my concern is - what is better place for it, since the change is in two files, but it doesn't feel right to complicate things much for little reason.
=> Add ShellCommand config option and change default to /bin/sh (on Unix)

README.md, goawk.go, internal/ast/ast.go, interp/interp.go, interp/interp_test.go, interp/io.go, lexer/lexer.go, lexer/token.go, parser/parser.go
This addresses some warnings mostly around the convention of the first
word of a godoc being the same as the exported symbol. This also
addresses some typos and some micronits. Any or all of this can be
dismissed if not welcome. I'm just raising this as noticed while
reviewing the code!
=> Addresses some IDE warnings relating to GoDoc comments

goawk_test.go, internal/ast/ast.go, interp/interp.go, interp/interp_test.go, lexer/lexer.go, lexer/lexer_test.go, parser/parser.go, parser/parser_test.go, parser/resolve.go
Parsing getline is tricky, and I needed to add a PeekByte function to
the lexer so the parser can tell the difference between "getline foo"
and "getline foo()".
There are still a few arcane forms not supported by GoAWK (see
commented-out interp tests), but most forms are supported now.
Also ensure data returned by getline is treated as numeric string.
Fixes #48.
=> Add support for "getline lvalue"

interp/interp.go, interp/interp_test.go
Not sure why the literal Unicode separators didn't work in Go source on Windows, but fix it.
=> Fix Unicode separator tests on Windows

.gitignore, csv.md, scripts/csvbench/csvbench.sh, scripts/csvbench/write.py, scripts/csvbench/write/main.go
Previously the read benchmarks (in `scripts/csvbench`) were using a file I had on my machine called `huge.csv`. I found it on the net at some stage but somehow I couldn't find it again. To avoid commit a huge file to source control, and avoid downloading a big file from the net, just have the read benchmark use the output of the write benchmark. Change this to a bit more complex CSV (20 fields, including several quoted fields) and make it 1GB in size.
Relative performance ratios are similar.
=> Update benchmarks to avoid huge.csv (read benchmark uses write output)

interp/interp_test.go, interp/io.go
The UTF-8 BOM was present at the start of some CSV files I found (maybe Excel writes it out?), [for example these ones](https://catalogue.data.govt.nz/dataset/directory-of-educational-institutions/resource/20b7c271-fd5a-4c9e-869b-481a0e2453cd), and it made the first field name `"\ufeff_id"` instead of `"_id"`.
=> Ignore UTF-8 BOM at start of CSV files

goawk.go, goawk_test.go, interp/io.go
This is odd, and doesn't seem to be explicitly stated in the POSIX spec, but it's how original-awk, mawk, and gawk all work. Portability trumps sanity. :-)
Fixes #129
=> Interpret escapes in -v and var=value arguments

goawk.go, interp/io.go, lexer/lexer.go, lexer/lexer_test.go
Instead of using Go's strconv.Unquote, we should use the same string
parsing we do in the GoAWK lexer. Refactor the string parsing in the
lexer slightly so we can add an Unescape function and use that.
=> More POSIX-accurate handling of cmdline var=value escaping

goawk.go, goawk_test.go, interp/interp.go, interp/io.go, testdata/awc.awk
It's like -f but stops processing other arguments and disables
foo=bar arguments in the rest of the args. Like Gawk's -E/--exec and
mawk's "-W exec" option.
Also update test runner to run Gawk and GoAWK tests in separate
sub-tests, so one breaking doesn't stop the other from running.
Fixes #139 (thanks @paulapatience)
=> Add support for -E argument (like Gawk's -E/--exec)

interp/interp_test.go, parser/parser.go
Fixes #145
Regarding the exception 2. this implementation relies on `p.stmtsBrace()` to consume the possible semicolon after the items ending in closing brace. But if that ever changes, the test cases should fail.
ps. sorry minor branch mistake, second try
=> Allow semicolon as terminator for an item

goawk.go, internal/parseutil/filereader.go, internal/parseutil/filereader_test.go
This is the other PR in context of #144.
This is re-implemenation of #150 based on work in #151. I think #151 can be just closed.
Basically this is almost equivalent to #151 plus:
1. added tests
2. added doc comments
3. applied minor optimization
=> Better filenames tracking

.github/workflows/tests.yml, interp/interp_test.go
They're failing in weird ways, for example:
```
GNU Awk 5.2.0, API 3.2, PMA Avon 7, (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)
Copyright (C) 1989, 1991-2022 Free Software Foundation.
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see …
```
=> Fix tests on macOS

goawk_test.go, interp/interp_test.go, parser/parser.go
This matches gawk/mawk/original-awk behaviour.
Add tests, also add test for ++rvalue syntax error.
Fixes #167
=> Make constructs like $++lvalue not an error

internal/compiler/compiler.go, internal/cover/cover.go, testdata/cover/a1_a2_covermode_count.awk, testdata/cover/a1_covermode_set.awk, testdata/cover/a2_covermode_count.awk, testdata/cover/a3_covermode_set.awk
When @xonixx was adding code coverage, I asked if he could make the coverage AST output __COVER["1"] instead of __COVER[1] to give a slight optimization. However, it's better to do that as an optimization that all users can benefit from instead.
The speedup for the ArrayOperations benchmark is about 11%, so I think it's worth it:
ArrayOperations-16   312ns ± 3%   276ns ± 3%  -11.54%  (p=0.008 n=5+5)
This commit adds the compiler optimization, but also makes the cover.go output __COVER[1] now that these expressions are optimized.
Fixes #157
=> Optimize constant integer array indexes to avoid toString() at runtime

interp/interp_test.go, parser/parser.go, testdata/gawk/badassign1.ok
Expressions like "1 && x=1" aren't really valid (IMO), because assignments are lower-precedence than binary operators, but onetrueawk, Gawk, and mawk all support this for logical, match and comparison operators.
The other awks support this by using a yacc grammar which supports backtracking, and as [Vitus13 said on reddit](https://www.reddit.com/r/ProgrammingLanguages/comments/10zfg1z/why_does_awk_parse_1x1_as_1x1_not_1x1_when_is/): "If there are two syntactically valid parsings and one is a semantic error, the error handling may resolve the ambiguity towards the valid parsing. In this case, you can only assign to L values, so trying to assign to (1&&x) doesn't make any sense."
In GoAWK, this requires a form of backtracking (I call it "partial backtracking" because it's not actually …
=> Allow parsing of "cond && var=value" and similar expressions

goawk_test.go, interp/interp_test.go
This avoids the following test failure when LC_ALL=C:
```
$ go test ./interp
--- FAIL: TestInterp (1.80s)
--- FAIL: TestInterp/awkposix_BEGIN_{_RS="ö"_}__{_print_}__#_!windows-gawk (0.00s)
interp_test.go:983: expected/got:
"1\ntwo\nthree\n"
"1\n\xb6two\n\xb6three\n"
FAIL
FAIL	github.com/benhoyt/goawk/interp	1.874s
FAIL
```
Also make the same change in goawk_test.go to avoid issues in future (though that doesn't fail right now).
Thanks to Jan Mercl for the bug report.
=> When running "gawk --posix", ensure we're using UTF-8

goawk_test.go, internal/ast/ast.go, internal/ast/walk.go, internal/compiler/compiler.go, internal/compiler/disassembler.go, internal/cover/cover.go, internal/resolver/resolve.go, interp/functions.go, interp/interp.go, interp/interp_test.go, interp/io.go, interp/newexecute.go, interp/vm.go, parser/parser.go, parser/parser_test.go, testdata/gawk/arrayparm.ok, testdata/gawk/arryref3.ok, testdata/gawk/arryref4.ok, testdata/gawk/arryref5.ok, testdata/gawk/aryprm4.ok, testdata/gawk/aryprm6.ok, testdata/gawk/aryprm7.ok, testdata/gawk/delfunc.ok, testdata/gawk/fnamedat.ok, testdata/gawk/fnarray.ok, testdata/gawk/fnarray2.ok, testdata/gawk/fnaryscl.ok, testdata/gawk/fnasgnm.ok, testdata/gawk/gsubasgn.ok, testdata/gawk/prmarscl.ok
This rewrites the type resolver to hopefully be easier to understand and change. We'll see.
Instead of trying to collect all information in a single pass, it now uses two passes:
1) First pass determines function call graph order (topological order).
2) Second pass determines variable type information.
Also:
* Simplify/stabilize "goawk -dt" output and add test
* Remove Scope and Index info from AST (that's a resolver thing)
* Improve error positions for several type errors (hence the updated col:line values in test output)
**Update:** I think this is definitely an improvement, as https://github.com/benhoyt/goawk/pull/176 (`length(x)` working for arrays as well as strings) was *much* simpler to implement with the new version.
=> Refactor and simplify resolver to use two passes

goawk.go, internal/resolver/resolve.go, interp/interp_test.go
As in f1's A parameter in this example, found by fuzzing:
```
function f1(A) {}  function f2(x, A) { x[0]; f1(a); f2(a) }
```
=> Do two resolver passes to ensure we set unknown param types

interp/interp_test.go, parser/parser.go, testdata/gawk/regexpbrack.ok
The parser checks regexes with regex.Compile, but when the compiler gets to it it adds regex flags, and some bad regexes pass the first but not the second.
=> Fix panic with certain obscure regexes

interp/interp.go, interp/interp_test.go
This is to prevent scripts like `ARGC=100000000` from taking forever. There are still lots of ways to make a script that runs for ages / forever of course, but it seems like we shouldn't allow arbitrarily large `ARGC` values.
=> Limit ARGC to a reasonable max value

goawk.go, goawk_test.go, internal/resolver/resolve.go, interp/interp_test.go, testdata/other/gron.awk
Fix "undefined function" error with mutually-recursive functions
When the AWK code defines mutually-recursive functions, the topological
sort can't help us. So define all funcInfos in the initial call-graph
pass before doing any resolver passes. This avoids the "undefined
function" error in those cases.
Add a minimal test for this, and also add a test of parsing/using the
gron.awk code, as it's a nice, fairly complex test case.
Fixes #183. Thanks @xonixx for the bug report!
=> Fix "undefined function" error with mutually-recursive functions

interp/interp_test.go
Per https://github.com/benhoyt/goawk/issues/183#issuecomment-1576732599, and given the two passes we do, the current test suite doesn't have any tests which require topoSort (topological sort of functions based on the call graph). Add a couple of these tests in case of regressions.
If you comment out the `topoSort` call, these tests fail with something like:
```
$ go run . -f t.awk
panic: internal error: found scalar when expecting array "c" [recovered]
panic: interface conversion: interface {} is string, not *compiler.compileError [recovered]
panic: interface conversion: interface {} is *runtime.TypeAssertionError, not *ast.PositionError
...
$ cat t.awk
function f1(a) { f2(a) }
function f2(b) { f3(b) }
function f3(c) { f4(c) }
function f4(d) { f5(d) }
function f5(i) { i[1]=42 }
BEGIN { …
```
=> Add tests that require topoSort

internal/resolver/resolve.go, interp/interp_test.go
Not exactly an elegant solution, but does the job and fixes the problem with resolving mutually-recursive functions.
Historical note: prior to introducing topological sorting this was the only way the type resolver did it, regardless of call graph. See https://github.com/benhoyt/goawk/commit/0bc9499481ee7775f1cc5fcca3bcac1443811bf4.
Fixes #186
=> Reintroduce additional resolve passes to fix complex mutual recursion

internal/compiler/compiler.go, internal/compiler/opcode_string.go, internal/compiler/opcodes.go, interp/interp_test.go, interp/vm.go
Also update stringer version, as I was getting this error with the current version for some reason:
https://github.com/golang/go/issues/52710
Fixes #191.
=> Ensure "exit" without status code doesn't set exit code

docs/csv.md, interp/functions.go, interp/interp.go, interp/interp_test.go, interp/vm.go
This is how awk and gawk's upcoming --csv feature works, so we want to be consistent. Note that it is a breaking change (hopefully a minor one, and only applies to people using CSV input mode).
=> Make two-argument split() respect CSV input mode

interp/io.go
The && operator causes conditional evaluation (aka "short-circuiting"). This means if the left-hand-side is false the right hand side is not evaluated. If any call to interp.flushWriter returns false then all streams following that stream in the range, as well as interp.output, will not be flushed.
Removes the type cast to the flusher interface because that is done in interp.flushWriter. This check would be performed twice for any interp.output value whose type implements the interface.
Fixes #208
=> flushAll() stops flushing on first error

goawk_test.go, interp/interp.go, interp/interp_test.go, interp/io.go, interp/iostream.go, interp/iostream_test.go, interp/newexecute.go, interp/vm.go
This creates the `inputStream` and `outputStream` interfaces which are satisfied by structs for all combinations of file/pipe and input/output:
1. Input File - `struct inFileStream`
2. Input Command - `struct inCmdStream`
3. Output File - `struct outFileStream`
4. Output Command - `struct outCmdStream`
The streams satisfy the `io.ReadCloser` and `io.WriteCloser` interfaces while the `outputStream` also has a `Flush() error` method. Both types of streams also have an `ExitCode() int` method which makes it trivial to determine the result of a `close()` on those streams.
This PR homogenizes behavior and fixes a number of minor issues related to command pipes. Gawk behavior is mimicked for the following:
1. The exit status of the child process is returned from `close()` when closing a pipe. …
=> Abstract redirects and pipes into inputStream and outputStream interface

interp/interp_test.go, lexer/lexer.go, lexer/lexer_test.go
See similar onetrueawk and Gawk changes:
- https://github.com/onetrueawk/awk/commit/ac3084de9b64d0c838e520ea1ebdb2e1bde87b3f
- https://git.savannah.gnu.org/cgit/gawk.git/commit/?id=1bc73bfb10f0600aaccca7220b5200e220f9a71a
Also, in lexer tests, stop after first error.
Fixes #210
=> Add support for new Unicode string escape \u

interp/interp_test.go
Here a fix for the test race condition in #206 and the test fail for Linux:
https://github.com/benhoyt/goawk/actions/runs/6293036690/job/17083040381.
I was able to reproduce on my older Macbook and Go 1.17 using `go test -count 1000 -run='TestInterp/^BEGIN { cmd'`... but not consistently. In my case the other pipe-to-command test failed (the one which uses `/bin/kill`) but with the same pipe error.
Analysis/commit message follows:
The bufio.Writer does not write to the Cmd pipe until Flush is called when the Cmd is Wait-ed on. This causes a Flush error but not a Wait error. This only happens if the Cmd starts and exits before the Flush can be called by goawk.
=> Fix rare race in pipe-to-command close() result test

interp/interp_test.go, interp/io.go
This pull request fixes issue #190 by introducing a custom split function that skips empty matches (according to https://www.austingroupbugs.net/view.php?id=1468, this is the correct behaviour). It is used only for FS
Fixes #190
=> Fix #190: FS regex [^,]* fails on empty field

interp/interp_test.go, parser/parser.go
Fixes #219. Thanks @oguz-ismail for the report.
=> Allow optional newline between "do {}" and "while"

internal/ast/ast.go, parser/parser.go, parser/parser_test.go
=> Distinguish between /regexp/ and "regexp" in stringified output

goawk_test.go, interp/interp_test.go, parser/parser.go
This pull request modifies `getLine()` inside parser.go so that it lets binary operators come after 'expr | getline' expressions.
I also uncommented two tests that were in TODO inside interp_test.go and added two new tests.
There were two other tests under the same TODO: (`BEGIN { print("echo foo" | getline ($0+1)); print }` and `BEGIN { print("echo foo" | getline foo()); print } function foo() { print "z" }`), but those address a separate issue.
Fixes #189
=> Fix wrong precedence of 'expr | getline' expressions

goawk_test.go, interp/interp_test.go
The en_US.UTF-8 locale is not guaranteed to be installed, and it quite often isn't by default.
The C.UTF-8 locale was introduced as a Debian-specific locale, but was later upstreamed into glibc 2.35 [1].
This patch fixes failures when running interpreter tests on systems where the en_US.UTF-8 locale is not present. It also changes the locale on goawk_test.go, similar to !174 [2].
1: https://sourceware.org/bugzilla/show_bug.cgi?id=17318
2: https://github.com/benhoyt/goawk/pull/174
---
I ran into some test failures when packaging goawk for Debian. I also ran the
test suite on a fresh Arch container, which failed for the same reason. This
seems like a reasonable fix :^)
=> Use C.UTF-8 as locale when invoking external awk program

interp/interp_test.go, interp/io.go
Fake it till Windows makes it. This enables the common pattern for printing messages to standard error:
print "An error!" >"/dev/stderr"
To work cross-platform on Windows as well as Unix-based OSs.
Fixes #195
=> Make redirecting to /dev/stderr work on Windows

.gitignore, internal/compiler/compiler.go, interp/interp_test.go
- '{}' shouldn't be equivalent to '{ print $0 }'
- 'END {}' should consume the input
Thanks @oguz-ismail
Fixes #228
=> Fix evaluation of empty {} and END{}

.github/workflows/tests.yml, internal/ast/ast.go, internal/compiler/compiler.go, internal/compiler/disassembler.go, interp/functions.go, interp/value.go, interp/vm.go
I don't know if this is the correct approach, but it looks fine. I also added Linux/386 tests on CI, but I don't know if you actually want this. I figured it would make it easier to verify that it works.
Closes #234
=> Fix number formatting on non-64bit architectures

interp/functions.go, interp/interp_test.go
I noticed goawk couldn't handle UTF-8 strings. While there already seems to be ample discussion about this, one of the UTF-8 features that doesn't seem to incur issues about O(n) speed is `printf("%c",[CODEPOINT])` which on the one true awk, Ray Gardner's awk, and gawk, will work with unicode codepoints and utf8 strings:
```
$ for awk in nawk gawk goawk; do $awk 'BEGIN {printf("%c", "ß")}' | xxd; done
00000000: c39f                                     ..
00000000: c39f                                     ..
00000000: c3                                       .
$ for awk in nawk gawk goawk; do $awk 'BEGIN {printf("%c", 400)}' | xxd; done
00000000: c690                                     ..
00000000: c690                                     ..
00000000: 90 …
```
=> Make printf %c work on Unicode codepoints

interp/functions.go, interp/interp_test.go
=> Add printf %i, %a, %A; Fix %o, %x, %X (they should be unsigned)

interp/interp_test.go, interp/vm.go
This is more POSIX-compatible. Fixes #231
=> Make srand() use unix time in seconds, and set seed for next srand()

goawk.go, goawk_test.go, interp/functions.go, interp/interp.go, interp/interp_test.go, interp/vm.go
Use chars mode in index(), length(), match(), and substr(). This is based on the work done in https://github.com/benhoyt/goawk/pull/83, but the default is the other way around (default = bytes mode, which is the same as it is now).
Also only use Unicode chars in `printf %c` if chars mode is enabled. This changes the default introduced in https://github.com/benhoyt/goawk/pull/236 / v1.28.0 for that feature.
This won't please everyone (defaults are the same as mawk, but not Gawk). But it's a pragmatic solution that allows people to opt into Unicode support if they want, and if they can handle the O(N) behaviour of those functions.
=> Add Unicode chars mode: "goawk -c" or Config.Chars=true
